version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: afsafeasdfkj;elkj332423!@#$
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./dbinit/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    ports:
      - $DB_PORT:$DB_PORT
    expose:
      - $DB_PORT
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    env_file:
      - ./.env
    environment:
      DB_HOST: mysqldb
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    ports:
      - $SERVER_PORT:$SERVER_PORT
    expose:
      - $SERVER_PORT
    depends_on:
      - mysqldb
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge
